@Presentation_HostAddress = https://localhost:7245

GET {{Presentation_HostAddress}}/api/Product

###

GET {{Presentation_HostAddress}}/api/Product/brands

###

GET {{Presentation_HostAddress}}/api/Product/types

###

@id=10
GET {{Presentation_HostAddress}}/api/Product/{{id}}

###
